#====================================================================================================
# Description : Demo of S3 bucket creation
# Version     : 1.0
#====================================================================================================
AWSTemplateFormatVersion: '2010-09-09'
Description: Demo of S3 bucket creation
#====================================================================================================
#                                             Parameters
#====================================================================================================

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true 

  
